import type { ViolationRule } from './types'

export const RULES: ViolationRule[] = [
  // ── Word Choice ──────────────────────────────────────────────────────────
  {
    id: 'overused-intensifiers',
    name: 'Overused Intensifier',
    category: 'word-choice',
    description: 'Words like "crucial," "vital," "robust," "leverage," "delve," etc. are LLM clichés that add noise.',
    tip: 'Delete it. If the sentence still makes sense, the word was never needed. If it doesn\'t, rewrite the sentence to show why it matters.',
    canRemove: true,
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.18)',
    rewriteHint: 'Remove overused intensifiers like "crucial", "vital", "robust", "leverage", "delve", "nuanced", "unprecedented" — delete them or restructure the sentence.',
    llmDirective: 'Remove the flagged overused intensifiers — delete them or rephrase the sentence without them.',
  },
  {
    id: 'elevated-register',
    name: 'Elevated Register',
    category: 'word-choice',
    description: 'Using "utilize" instead of "use," "commence" instead of "start," "facilitate" instead of "help."',
    tip: 'Replace with the simpler word. "Utilize" → "use." "Commence" → "start." Elevated register performs intelligence rather than demonstrating it.',
    canRemove: false,
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.18)',
    rewriteHint: 'Replace elevated vocabulary with simpler words: utilize→use, commence→start, facilitate→help, endeavor→try, demonstrate→show, craft→write/make.',
    llmDirective: "Replace elevated register with plain equivalents: 'utilize'→'use', 'commence'→'start', 'facilitate'→'help', 'endeavor'→'try', 'demonstrate'→'show'.",
  },
  {
    id: 'filler-adverbs',
    name: 'Filler Adverb',
    category: 'word-choice',
    description: '"Importantly," "essentially," "fundamentally," "ultimately," "inherently" signal importance without substantiating it.',
    tip: 'Remove it. If the sentence still works, the adverb was empty. If it doesn\'t work without it, the sentence needs to be rewritten to earn the emphasis.',
    canRemove: true,
    color: '#eab308',
    bgColor: 'rgba(234,179,8,0.18)',
    rewriteHint: 'Delete sentence-opening filler adverbs: importantly, essentially, fundamentally, ultimately, inherently.',
    llmDirective: 'Do not open sentences with filler adverbs (importantly, essentially, fundamentally, ultimately, inherently).',
  },
  {
    id: 'almost-hedge',
    name: '"Almost" Hedge',
    category: 'word-choice',
    description: '"Almost always," "almost never," "almost certainly" — hedging instead of committing to the pattern.',
    tip: 'Commit. "Almost always" → "usually." Or just say "always" and defend the claim. Readers notice when you won\'t take a stance.',
    canRemove: false,
    color: '#84cc16',
    bgColor: 'rgba(132,204,22,0.18)',
    rewriteHint: 'Replace "almost always/never/certainly" with a direct claim or a precise qualifier like "usually" or "rarely".',
    llmDirective: "Do not hedge with 'almost always', 'almost never', 'almost certainly' — commit to the claim directly.",
  },
  {
    id: 'era-opener',
    name: '"In an Era of…"',
    category: 'word-choice',
    description: 'Opening phrase that stalls before reaching the actual argument.',
    tip: 'Delete this clause entirely and start the sentence at the real point. "In an era of rapid change, companies must adapt" → "Companies must adapt."',
    canRemove: false,
    color: '#22d3ee',
    bgColor: 'rgba(34,211,238,0.15)',
    rewriteHint: 'Delete era-opener clauses ("In an era of...", "In a world where...") and start at the real point.',
    llmDirective: "Do not open with era-framing clauses ('In an era of...', 'In a world where...') — start at the real point.",
  },

  {
    id: 'operational-jargon',
    name: 'Operational Jargon',
    category: 'word-choice',
    description: 'Terms borrowed from engineering used as analytical-sounding shorthand: "pressure test," "failure mode."',
    tip: 'Replace with what you actually mean. "Pressure test" → "test." "Failure mode" → "way it could fail." Jargon signals borrowed authority rather than an actual argument.',
    canRemove: false,
    color: '#9333ea',
    bgColor: 'rgba(147,51,234,0.15)',
    rewriteHint: 'Replace with plain language: "pressure test" → "test", "failure mode" → "way it could fail".',
    llmDirective: 'Replace engineering jargon with plain language: "pressure test" → "test", "failure mode" → "way it could fail".',
  },

  // ── Framing ──────────────────────────────────────────────────────────────
  {
    id: 'metaphor-crutch',
    name: 'Metaphor Crutch',
    category: 'framing',
    description: 'Predictable metaphors: "double-edged sword," "tip of the iceberg," "north star," "game-changer," etc.',
    tip: 'Either find a specific, original image from the actual subject matter, or drop the metaphor and say the thing plainly.',
    canRemove: false,
    color: '#a78bfa',
    bgColor: 'rgba(167,139,250,0.18)',
    rewriteHint: 'Replace clichéd metaphors (double-edged sword, north star, game-changer, deep dive) with plain language or a specific concrete image.',
    llmDirective: 'Replace the flagged clichéd metaphors with plain language or a specific concrete image.',
  },
  {
    id: 'broader-implications',
    name: '"Broader Implications"',
    category: 'framing',
    description: 'Zooming out to claim significance without substantiation.',
    tip: 'State the implication explicitly, or cut the phrase. "This has broader implications" says nothing. What are the implications? Say them.',
    canRemove: false,
    color: '#38bdf8',
    bgColor: 'rgba(56,189,248,0.15)',
    rewriteHint: 'Replace "broader/wider implications" with the actual specific implication, or delete the phrase.',
    llmDirective: "Do not use 'broader implications' or 'wider implications' — state the actual implication or delete the phrase.",
  },

  // ── Sentence Structure ───────────────────────────────────────────────────
  {
    id: 'em-dash-pivot',
    name: 'Em-Dash Overuse',
    category: 'sentence-structure',
    description: 'Em-dashes used as catch-all punctuation instead of choosing the right mark.',
    tip: 'Ask what relationship this dash is expressing. A pause → comma. A list → colon. A parenthetical → parentheses. A new sentence → period. Choose the right tool.',
    canRemove: false,
    color: '#fb7185',
    bgColor: 'rgba(251,113,133,0.18)',
    rewriteHint: 'Replace em-dashes with appropriate punctuation: comma for a pause, colon for elaboration, parentheses for an aside, period for a new sentence.',
    llmDirective: 'Do not use em-dashes (—). Replace each with the correct punctuation: comma for a pause, colon for elaboration, parentheses for an aside, period for a new sentence.',
  },
  {
    id: 'negation-pivot',
    name: 'Negation Pivot',
    category: 'sentence-structure',
    description: '"Not X, but Y" / "don\'t X, but Y" — negation followed by reframe. A hallmark LLM rhetorical structure.',
    tip: 'Rewrite as a direct positive claim. "We don\'t constrain through prohibition, but through amplification" → "We constrain through amplification." Lead with what is true, not what isn\'t.',
    canRemove: false,
    color: '#f43f5e',
    bgColor: 'rgba(244,63,94,0.15)',
    rewriteHint: 'Rewrite "not X, but Y" constructions as direct positive claims. Lead with what is true, not what isn\'t.',
    llmDirective: "Do not use 'not X, but Y' constructions — rewrite as a direct positive claim.",
  },
  {
    id: 'colon-elaboration',
    name: 'Colon Elaboration',
    category: 'sentence-structure',
    description: 'Short declarative clause, colon, then longer explanation — a mechanical LLM sentence pattern.',
    tip: 'Either merge into one flowing sentence, or make two separate sentences. The colon-elaboration structure becomes predictable when used repeatedly.',
    canRemove: false,
    color: '#f472b6',
    bgColor: 'rgba(244,114,182,0.15)',
    rewriteHint: 'Rewrite colon-elaboration sentences ("X: [long explanation]") by merging into one flowing sentence or splitting into two separate sentences.',
    llmDirective: "Do not use the '[short clause]: [long elaboration]' sentence structure — merge into one sentence or split into two.",
  },
  {
    id: 'question-then-answer',
    name: 'Question-Then-Answer',
    category: 'sentence-structure',
    description: 'Rhetorical question immediately followed by its own answer.',
    tip: 'Delete the question and just make the statement. "What does this mean? It means X." → "This means X."',
    canRemove: false,
    color: '#34d399',
    bgColor: 'rgba(52,211,153,0.15)',
    rewriteHint: 'Delete rhetorical questions and make the statement directly. "What does this mean? It means X." → "This means X."',
    llmDirective: 'Do not write a rhetorical question immediately followed by its own answer — delete the question and make the statement directly.',
  },
  {
    id: 'staccato-burst',
    name: 'Staccato Burst',
    category: 'sentence-structure',
    description: 'Three or more consecutive very short sentences at matching cadence.',
    tip: 'Vary the rhythm. Combine some of these sentences, or expand one into a full thought. Uniform short sentences feel like a list of bullet points in disguise.',
    canRemove: false,
    color: '#60a5fa',
    bgColor: 'rgba(96,165,250,0.15)',
    rewriteHint: 'Break up staccato burst of short sentences by combining some or expanding one into a full thought with varied rhythm.',
    llmDirective: 'Do not write three or more consecutive very short sentences at matching rhythm — vary sentence length and structure.',
  },
  {
    id: 'hedge-stack',
    name: 'Hedge Stack',
    category: 'sentence-structure',
    description: 'Multiple hedges in one sentence: "perhaps," "arguably," "might," "could," "seemingly," etc.',
    tip: 'Pick one hedge if you need it, remove the rest. Better: commit to the claim and let the reader evaluate it. Five hedges communicate nothing.',
    canRemove: false,
    color: '#4ade80',
    bgColor: 'rgba(74,222,128,0.15)',
    rewriteHint: 'Remove stacked hedges (perhaps, arguably, might, could, seemingly). Keep at most one if genuinely needed; otherwise commit to the claim.',
    llmDirective: 'Do not stack multiple hedges in one sentence (perhaps, arguably, might, could, seemingly) — keep at most one.',
  },
  {
    id: 'parenthetical-qualifier',
    name: 'Parenthetical Qualifier',
    category: 'sentence-structure',
    description: 'Parenthetical asides that perform nuance without changing the argument.',
    tip: 'Either make the qualification part of the main sentence (it\'s important enough to say plainly) or delete it (it wasn\'t needed).',
    canRemove: true,
    color: '#c084fc',
    bgColor: 'rgba(192,132,252,0.15)',
    rewriteHint: 'Cut parenthetical qualifiers (of course, to be fair, admittedly, needless to say) — integrate if essential, delete otherwise.',
    llmDirective: 'Remove the flagged parenthetical qualifiers (of course, to be fair, admittedly) — integrate the content or delete it.',
  },
  {
    id: 'unnecessary-contrast',
    name: 'Unnecessary Contrast',
    category: 'sentence-structure',
    description: '"Whereas," "as opposed to," "unlike" used to restate what the first clause already implied.',
    tip: 'Delete the contrasting clause. If it adds information the reader didn\'t have, rewrite it as a direct statement rather than a contrast.',
    canRemove: false,
    color: '#f87171',
    bgColor: 'rgba(248,113,113,0.15)',
    rewriteHint: 'Remove unnecessary contrast markers (whereas, as opposed to, unlike, in contrast to) — restate as a direct claim.',
    llmDirective: 'Do not use unnecessary contrast markers (whereas, as opposed to, unlike, in contrast to) — state the claim directly.',
  },

  // ── Rhetorical ───────────────────────────────────────────────────────────
  {
    id: 'important-to-note',
    name: '"It\'s Important to Note"',
    category: 'rhetorical',
    description: 'Verbal tic that precedes qualifications — tells the reader what to think before saying the thing.',
    tip: 'Delete the phrase and just say the thing. "It\'s important to note that X" → "X."',
    canRemove: false,
    color: '#fbbf24',
    bgColor: 'rgba(251,191,36,0.18)',
    rewriteHint: 'Delete "it is important to note", "it\'s worth noting", "it should be noted" — just say the thing.',
    llmDirective: "Do not use 'it is important to note', 'it\\'s worth noting', or 'it should be noted' — just say the thing.",
  },
  {
    id: 'false-conclusion',
    name: 'False Conclusion',
    category: 'rhetorical',
    description: '"At the end of the day," "in conclusion," "to summarize" — high-school essay signposting.',
    tip: 'Delete the phrase. The conclusion should land through its content, not be announced. If you need to say "in conclusion," the conclusion isn\'t clear enough.',
    canRemove: false,
    color: '#e879f9',
    bgColor: 'rgba(232,121,249,0.15)',
    rewriteHint: 'Delete conclusion signpost phrases (in conclusion, at the end of the day, to summarize, moving forward) — let the content land without announcement.',
    llmDirective: 'Do not use conclusion signpost phrases (in conclusion, at the end of the day, to summarize, moving forward) — let the content land without announcement.',
  },
  {
    id: 'connector-addiction',
    name: 'Connector Addiction',
    category: 'rhetorical',
    description: 'Every paragraph opened with a transition word: "Furthermore," "Moreover," "Additionally," etc.',
    tip: 'Delete the transition and let the ideas connect through their content. If the connection isn\'t obvious without the word, restructure — don\'t signal.',
    canRemove: false,
    color: '#2dd4bf',
    bgColor: 'rgba(45,212,191,0.15)',
    rewriteHint: 'Delete paragraph-opening connectors (Furthermore, Moreover, Additionally, However, That said) — let the ideas connect through their content.',
    llmDirective: 'Do not open paragraphs with transitional connectors (Furthermore, Moreover, Additionally, However, That said) — let ideas connect through their content.',
  },

  // ── Structural ───────────────────────────────────────────────────────────
  {
    id: 'listicle-instinct',
    name: 'Listicle Instinct',
    category: 'structural',
    description: 'Lists with exactly 3, 5, 7, or 10 items — LLMs default to these magic numbers.',
    tip: 'Ask if this really needs a list. If the items have natural prose flow, write them as prose. If it is a list, let it have the number of items it actually has — 4, 6, 9.',
    canRemove: false,
    color: '#fb923c',
    bgColor: 'rgba(251,146,60,0.15)',
    rewriteHint: 'If the list has natural prose flow, rewrite as prose. If keeping as a list, give it its natural number of items rather than a magic number.',
    llmDirective: 'Do not use lists with exactly 3, 5, 7, or 10 items — write as prose or use the natural number of items.',
  },

  // ── Sentence Structure (new) ─────────────────────────────────────────────
  {
    id: 'serves-as',
    name: '"Serves As" Dodge',
    category: 'sentence-structure',
    description: 'Replacing "is/are" with pompous alternatives: "serves as," "stands as," "acts as," "functions as."',
    tip: 'Replace with "is" or "are." The pompous substitute performs sophistication without adding meaning.',
    canRemove: false,
    color: '#818cf8',
    bgColor: 'rgba(129,140,248,0.18)',
    rewriteHint: 'Replace "serves as", "stands as", "acts as", "functions as" with "is" or "are".',
    llmDirective: "Replace 'serves as', 'stands as', 'acts as', 'functions as' with 'is' or 'are'.",
  },
  {
    id: 'negation-countdown',
    name: '"Not X. Not Y. Just Z."',
    category: 'sentence-structure',
    description: '2+ consecutive sentences starting with "Not " — building tension by negating before revealing.',
    tip: 'Cut the negations and state the positive claim directly.',
    canRemove: false,
    color: '#fb7185',
    bgColor: 'rgba(251,113,133,0.15)',
    rewriteHint: 'Replace the "Not X. Not Y. Just Z." pattern with a single direct positive statement.',
    llmDirective: 'Do not use the "Not X. Not Y. Just Z." pattern — replace with a single direct positive statement.',
  },
  {
    id: 'anaphora-abuse',
    name: 'Anaphora Abuse',
    category: 'sentence-structure',
    description: '3+ consecutive sentences starting with the same two-word opener.',
    tip: 'Vary the sentence openings. Anaphora becomes a tic when used more than twice.',
    canRemove: false,
    color: '#22d3ee',
    bgColor: 'rgba(34,211,238,0.15)',
    rewriteHint: 'Vary sentence openings — break the anaphoric repetition by restructuring some sentences.',
    llmDirective: 'Do not repeat the same sentence opener three or more times consecutively — vary sentence openings.',
  },
  {
    id: 'gerund-litany',
    name: 'Gerund Fragment Litany',
    category: 'sentence-structure',
    description: '2+ consecutive short sentences (≤8 words) starting with a capital -ing word.',
    tip: 'Expand these into full sentences or merge them. The gerund litany is a mechanical rhythm.',
    canRemove: false,
    color: '#84cc16',
    bgColor: 'rgba(132,204,22,0.15)',
    rewriteHint: 'Expand gerund sentence fragments into full sentences or merge them together.',
    llmDirective: 'Do not write multiple consecutive short sentences starting with gerunds — expand or merge them.',
  },
  {
    id: 'superficial-analysis',
    name: 'Superficial Analysis',
    category: 'sentence-structure',
    description: 'Trailing participle phrase claiming false significance: ", highlighting its importance," ", underscoring its role," etc.',
    tip: 'Cut the trailing phrase entirely. If the significance is real, make it a separate sentence with a specific claim.',
    canRemove: true,
    color: '#2dd4bf',
    bgColor: 'rgba(45,212,191,0.15)',
    rewriteHint: 'Cut trailing significance phrases like ", highlighting its importance," ", underscoring its role," etc.',
    llmDirective: "Remove trailing significance phrases such as ', highlighting its importance,' or ', underscoring its role,' entirely.",
  },

  // ── Rhetorical (new) ─────────────────────────────────────────────────────
  {
    id: 'heres-the-kicker',
    name: '"Here\'s the Kicker"',
    category: 'rhetorical',
    description: 'False suspense transitions: "here\'s the kicker," "here\'s the thing," "here\'s where it gets interesting," etc.',
    tip: 'Delete the transition and state the point directly.',
    canRemove: true,
    color: '#d946ef',
    bgColor: 'rgba(217,70,239,0.15)',
    rewriteHint: 'Delete false suspense transitions ("Here\'s the thing", "Here\'s the kicker", "Here\'s where it gets interesting") and state the point directly.',
    llmDirective: "Do not use false suspense transitions ('Here\\'s the thing', 'Here\\'s the kicker', 'Here\\'s where it gets interesting') — state the point directly.",
  },
  {
    id: 'pedagogical-aside',
    name: 'Pedagogical Aside',
    category: 'rhetorical',
    description: 'Teacher-mode phrases: "let\'s break this down," "let\'s unpack," "think of it as," etc.',
    tip: 'Skip the preamble and explain the thing directly. The reader doesn\'t need to be managed.',
    canRemove: false,
    color: '#0ea5e9',
    bgColor: 'rgba(14,165,233,0.15)',
    rewriteHint: 'Remove teacher-mode preambles ("let\'s break this down", "let\'s unpack", "think of it as") and explain directly.',
    llmDirective: "Do not use teacher-mode preambles ('Let\\'s break this down', 'Let\\'s unpack', 'Think of it as') — explain directly.",
  },
  {
    id: 'imagine-world',
    name: '"Imagine a World Where"',
    category: 'rhetorical',
    description: 'Opens with a futurist invitation: "Imagine a world," "Imagine if you," "Imagine what would," "Imagine a future."',
    tip: 'Start with the actual argument instead of inviting the reader to imagine it.',
    canRemove: false,
    color: '#7c3aed',
    bgColor: 'rgba(124,58,237,0.15)',
    rewriteHint: 'Delete "Imagine a world where..." opener and start with the actual argument.',
    llmDirective: "Do not open with hypothetical world-building ('Imagine a world where...') — start with the actual argument.",
  },
  {
    id: 'vague-attribution',
    name: 'Vague Attribution',
    category: 'rhetorical',
    description: 'Unnamed authority invocations: "experts argue," "studies show," "observers have noted," "research suggests," etc.',
    tip: 'Name the experts, cite the studies, or drop the claim. Vague attribution is worse than no citation.',
    canRemove: false,
    color: '#64748b',
    bgColor: 'rgba(100,116,139,0.15)',
    rewriteHint: 'Replace vague attribution (experts argue, studies show, research suggests) with a named source, or drop the claim entirely.',
    llmDirective: "Do not use vague attribution ('experts argue', 'studies show', 'research suggests') — name the source or drop the claim.",
  },
  {
    id: 'despite-challenges',
    name: '"Despite Its Challenges"',
    category: 'rhetorical',
    description: 'Formula: "Despite [these/its/the] [challenges/obstacles/limitations]..." — conceding without substance.',
    tip: 'Name the specific challenge. "Despite its challenges" is a throat-clear disguised as an acknowledgment.',
    canRemove: false,
    color: '#10b981',
    bgColor: 'rgba(16,185,129,0.15)',
    rewriteHint: 'Replace "despite its/these challenges" with the specific named challenge, or cut the concession.',
    llmDirective: "Do not use 'despite its challenges', 'despite these limitations', or similar empty concessions — name the specific challenge or cut it.",
  },

  // ── Structural (new) ─────────────────────────────────────────────────────
  {
    id: 'listicle-trench-coat',
    name: 'Listicle in a Trench Coat',
    category: 'structural',
    description: '"The first... The second... The third..." — prose disguising a list.',
    tip: 'Either use an actual list or rewrite as genuine prose. Don\'t pretend a list is an argument.',
    canRemove: false,
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.15)',
    rewriteHint: 'Rewrite "The first... The second... The third..." as either a real bullet list or genuine prose where ideas connect through logic rather than ordinal markers.',
    llmDirective: 'Do not use ordinal prose disguising a list ("The first... The second... The third...") — write as real prose or use an actual list.',
  },
  {
    id: 'bold-first-bullets',
    name: 'Bold-First Bullets',
    category: 'structural',
    description: 'Markdown list items starting with a bolded phrase: "- **Term**: explanation."',
    tip: 'Either use a definition list format or integrate the bold label into prose. This is pure LLM document structure.',
    canRemove: false,
    color: '#ca8a04',
    bgColor: 'rgba(202,138,4,0.15)',
    rewriteHint: 'Rewrite bold-first bullet points as prose sentences that integrate the label naturally.',
    llmDirective: 'Do not use bold-first bullet formatting (**Term**: explanation) — integrate into prose.',
  },
  {
    id: 'unicode-arrows',
    name: 'Unicode Decoration',
    category: 'structural',
    description: 'The → arrow character used in prose as a decoration or shorthand.',
    tip: 'Write out the relationship. "Input → Output" → "Input produces Output."',
    canRemove: false,
    color: '#475569',
    bgColor: 'rgba(71,85,105,0.15)',
    rewriteHint: 'Replace → arrows with the written-out relationship (produces, leads to, becomes, results in).',
    llmDirective: 'Do not use → arrows in prose — write out the relationship (produces, leads to, becomes).',
  },
  {
    id: 'dramatic-fragment',
    name: 'Dramatic Fragment',
    category: 'structural',
    description: 'A standalone paragraph with ≤4 words — used for false dramatic emphasis.',
    tip: 'Either expand it into a real sentence or absorb it into the surrounding paragraph.',
    canRemove: false,
    color: '#f43f5e',
    bgColor: 'rgba(244,63,94,0.15)',
    rewriteHint: 'Absorb this short dramatic fragment into the surrounding paragraph or expand it into a complete thought.',
    llmDirective: 'Do not use a one-to-four-word standalone paragraph for dramatic emphasis — absorb it into the surrounding text.',
  },

  // ── Framing (new) ────────────────────────────────────────────────────────
  {
    id: 'concept-label',
    name: 'Invented Concept Label',
    category: 'framing',
    description: 'Compound noun + abstract suffix used as an invented analytical term: "the attention paradox," "the trust vacuum," "the context creep."',
    tip: 'Either explain the phenomenon in plain terms or use an established name for it.',
    canRemove: false,
    color: '#c084fc',
    bgColor: 'rgba(192,132,252,0.15)',
    rewriteHint: 'Replace invented concept labels ("the X paradox", "the Y vacuum") with plain description of the actual phenomenon.',
    llmDirective: "Do not use invented concept labels ('the X paradox', 'the Y vacuum', 'the Z creep') — describe the phenomenon in plain terms.",
  },

  {
    id: 'short-hook-paragraph',
    name: 'Short-Hook Paragraph',
    category: 'sentence-structure',
    description: 'A short punchy opener (≤10 words) followed by two or more substantially longer elaboration sentences — the LLM "hook then evidence pile" rhythm.',
    tip: 'Expand the opener into a complete thought, or absorb it into the first elaboration sentence. The sharp length contrast signals formulaic structure.',
    canRemove: false,
    color: '#22d3ee',
    bgColor: 'rgba(34,211,238,0.15)',
    rewriteHint: 'Expand this short opener into a complete sentence, or merge it with the sentence that follows.',
    llmDirective: 'Do not open a paragraph with a short punchy fragment followed by a pile of longer elaboration sentences — develop the opening idea fully.',
  },

  {
    id: 'triple-construction',
    name: 'Triple Construction',
    category: 'sentence-structure',
    description: 'Exactly three parallel items: "X, Y, and Z" — LLMs default to threes compulsively.',
    tip: 'Break the pattern. Use two items or four. Or convert one item into its own sentence to give it more weight.',
    canRemove: false,
    color: '#a3e635',
    bgColor: 'rgba(163,230,53,0.15)',
    rewriteHint: 'Break the rule-of-three pattern (X, Y, and Z) — use two items, four items, or give one item its own sentence.',
    llmDirective: 'Do not use the rule of three (X, Y, and Z) — use two items, four items, or give one item its own sentence.',
  },
  {
    id: 'false-range',
    name: 'False Range',
    category: 'sentence-structure',
    description: '"From X to Y" constructions where X and Y aren\'t on a meaningful spectrum, or hollow idioms like "doesn\'t emerge from nowhere".',
    tip: 'Either show a real spectrum or cut the framing entirely.',
    canRemove: false,
    color: '#fbbf24',
    bgColor: 'rgba(251,191,36,0.15)',
    rewriteHint: 'Replace hollow "from X to Y" constructions with direct language. Cut "doesn\'t come from nowhere" and similar clichés.',
    llmDirective: "Do not use hollow 'from X to Y' constructions or clichéd idioms like 'doesn't come from nowhere' — use direct language.",
  },

  {
    id: 'pseudo-rigor',
    name: 'Pseudo-Rigor',
    category: 'framing',
    description: 'Performing the appearance of evaluation without naming any standard: "defensible," "hard to argue with," "stands up to scrutiny."',
    tip: 'Name the actual standard. If it\'s "defensible," defensible against what objection? Show the test, don\'t signal it.',
    canRemove: false,
    color: '#0f766e',
    bgColor: 'rgba(15,118,110,0.15)',
    rewriteHint: 'Replace "defensible/hard to argue with/stands up to scrutiny" with the actual reason the choice holds — name the objection it answers.',
    llmDirective: 'Do not signal rigor with words like "defensible" or "hard to argue with" — name the actual standard or objection the argument answers.',
  },

  {
    id: 'unnecessary-quotes',
    name: 'Unnecessary Quotes',
    category: 'word-choice',
    description: 'Quotation marks used for emphasis rather than to mark speech, irony, or a coined term.',
    tip: 'Use italics for emphasis. Reserve quotes for speech, irony, or introducing someone else\'s term.',
    canRemove: false,
    color: '#06b6d4',
    bgColor: 'rgba(6,182,212,0.15)',
  },
  {
    id: 'privileged-insight',
    name: 'Privileged Insight',
    category: 'framing',
    description: 'Asserting that the real truth is obvious or that the reader is missing the actual point — without proving it.',
    tip: 'If the truth were obvious, you wouldn\'t need to say so. Make the argument instead of announcing it.',
    canRemove: false,
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.15)',
  },

]

export const RULES_BY_ID = Object.fromEntries(RULES.map(r => [r.id, r]))
